-- ============================================
-- Table: employees
-- Description: Auto-generated table structure
-- Generated: 2026-06-06 15:09:06
-- ============================================

CREATE TABLE IF NOT EXISTS `employees` (
  `id` VARCHAR(36) NOT NULL COMMENT 'Primary Key - UUID v4',
  `full_name` VARCHAR(255) NOT NULL COMMENT 'Full Name',
  `company_name` VARCHAR(255) NOT NULL COMMENT 'Company Name',
  `position` VARCHAR(255) NOT NULL COMMENT 'Position',
  `employee_id` VARCHAR(255) NOT NULL COMMENT 'Employee Id',
  `bpjs_tenaker_no` VARCHAR(255) NOT NULL COMMENT 'BPJS Tenaker No',
  `bpjs_kes_no` VARCHAR(255) NOT NULL COMMENT 'BPJS Kes No',
  `merdeka_sehat` VARCHAR(255) NOT NULL COMMENT 'Merdeka Sehat',
  `mine_permit` VARCHAR(255) NOT NULL COMMENT 'mine_permit',
  `induction_schedule` DATE NOT NULL COMMENT 'Induction Schedule',
  `mine_permit_scm` VARCHAR(255) NOT NULL COMMENT 'Mine Permit SCM',
  `simper_teory_test` VARCHAR(255) NOT NULL COMMENT 'Simper Teory Test',
  `simper_practice_test` VARCHAR(255) NOT NULL COMMENT 'Simper practice Test',
  `simper_ojt` VARCHAR(255) NOT NULL COMMENT 'Simper OJT',
  `simper_status` VARCHAR(255) NOT NULL COMMENT 'Simper Status',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Auto-generated table';

-- ============================================
-- Sample Data (Commented)
-- ============================================
-- INSERT INTO `employees` (`id`, `full_name`, `company_name`, `position`, `employee_id`, `bpjs_tenaker_no`, `bpjs_kes_no`, `merdeka_sehat`, `mine_permit`, `induction_schedule`, `mine_permit_scm`, `simper_teory_test`, `simper_practice_test`, `simper_ojt`, `simper_status`) VALUES
-- ('sample-uuid-here', 'Sample Full Name', 'Sample Company Name', 'Sample Position', 'Sample Employee Id', 'Sample BPJS Tenaker No', 'Sample BPJS Kes No', 'Sample Merdeka Sehat', 'Sample mine_permit', 'Sample Induction Schedule', 'Sample Mine Permit SCM', 'Sample Simper Teory Test', 'Sample Simper practice Test', 'Sample Simper OJT', 'Sample Simper Status');

-- ============================================
-- Notes:
-- - Primary key uses UUID v4 format (36 characters)
-- - All VARCHAR fields use utf8mb4_unicode_ci collation
-- ============================================

-- ADD NEW COLUMNS
ALTER TABLE `employees` 
ADD COLUMN `gaji_pokok` INT DEFAULT 0 COMMENT 'Gaji Pokok',
ADD COLUMN `tunjangan_tetap` INT DEFAULT 0 COMMENT 'Tunjangan Tetap';

-- MODIFY EXISTING COLUMNS TO INT (If already created)
-- ALTER TABLE `employees` MODIFY COLUMN `gaji_pokok` INT DEFAULT 0 COMMENT 'Gaji Pokok', MODIFY COLUMN `tunjangan_tetap` INT DEFAULT 0 COMMENT 'Tunjangan Tetap';

INSERT INTO employees SET id = 'C027337Imanuel', full_name= 'Imanuel', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver LV', employee_id='C027337', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='DONE', simper_status='Simper PermanentSimper Permanent';
INSERT INTO employees SET id = 'C027326Rino', full_name= 'Rino', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C027326', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='DONE', simper_status='Simper PermanentSimper Permanent';
INSERT INTO employees SET id = 'C027335Isran', full_name= 'Isran', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C027335', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='DONE', simper_status='Simper PermanentSimper Permanent';
INSERT INTO employees SET id = 'C027334ABD', full_name= 'ABD Hamid', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C027334', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='DONE', simper_status='Simper PermanentSimper Permanent';
INSERT INTO employees SET id = 'C027669Sarman', full_name= 'Sarman', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C027669', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-30', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='DONE', simper_status='Simper PermanentSimper Permanent';
INSERT INTO employees SET id = 'C027643Ettuin', full_name= 'Ettuin', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C027643', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-30', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='DONE', simper_status='Simper PermanentSimper Permanent';
INSERT INTO employees SET id = 'C027627Bagus', full_name= 'Bagus Handoko', company_name='PT Pelangi Utama Jaya Mandiri', position='SPV Operation', employee_id='C027627', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-05-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='DONE', simper_status='Simper PermanentSimper Permanent';
INSERT INTO employees SET id = 'C027672M' ,full_name= 'M Syukur', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Bulldozer', employee_id='C027672', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-05-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='DONE', simper_status='Simper PermanentSimper Permanent';
INSERT INTO employees SET id = 'C028909Syukri', full_name= 'Syukri Gais', company_name='PT Pelangi Utama Jaya Mandiri', position='Spv Trainer', employee_id='C028909', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-05-14', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='DONE', simper_status='Simper PermanentSimper Permanent';
INSERT INTO employees SET id = 'C028687M' ,full_name= 'M Dzul Iqram', company_name='PT Pelangi Utama Jaya Mandiri', position='Spv HSE', employee_id='C028687', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-05-14', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='DONE', simper_status='Simper PermanentSimper Permanent';
INSERT INTO employees SET id = 'C027349Adam', full_name= 'Adam Yordan', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C027349', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='Simper TemporarySimper Temporary';
INSERT INTO employees SET id = 'C027332Yusdin', full_name= 'Yusdin', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C027332', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='Simper TemporarySimper Temporary';
INSERT INTO employees SET id = 'C027329Jasrin', full_name= 'Jasrin', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C027329', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='Simper TemporarySimper Temporary';
INSERT INTO employees SET id = 'C027331Yusrin', full_name= 'Yusrin', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C027331', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='Simper TemporarySimper Temporary';
INSERT INTO employees SET id = 'C027635Joni', full_name= 'Joni Hariyanto', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C027635', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='Simper TemporarySimper Temporary';
INSERT INTO employees SET id = 'C027637A' ,full_name= 'A Ali Imran Jabar', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C027637', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-27', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='Simper TemporarySimper Temporary';
INSERT INTO employees SET id = 'C027642Asriadi', full_name= 'Asriadi', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C027642', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-27', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='Simper TemporarySimper Temporary';
INSERT INTO employees SET id = 'C027641Asran', full_name= 'Asran Lamio', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Bulldozer', employee_id='C027641', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-27', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='Simper TemporarySimper Temporary';
INSERT INTO employees SET id = 'C027671Yusran', full_name= 'Yusran', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Vibro', employee_id='C027671', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-30', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='Simper TemporarySimper Temporary';
INSERT INTO employees SET id = 'C027636Samsul', full_name= 'Samsul Anwar', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C027636', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-30', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='Simper TemporarySimper Temporary';
INSERT INTO employees SET id = 'C027662Iksan', full_name= 'Iksan', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Braker', employee_id='C027662', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-05-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='Simper TemporarySimper Temporary';
INSERT INTO employees SET id = 'C027634Andri', full_name= 'Andri Afiyanto', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C027634', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-05-04', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='Simper TemporarySimper Temporary';
INSERT INTO employees SET id = 'C029951ISRA', full_name= 'ISRA JAYA', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C029951', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-05-31', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='On Progress On Progress ';
INSERT INTO employees SET id = 'C029974ULIL', full_name= 'ULIL ALBAB', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Vibro', employee_id='C029974', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-05-31', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='On Progress On Progress ';
INSERT INTO employees SET id = 'C027640AFRUL', full_name= 'AFRUL', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C027640', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-05-31', mine_permit_scm='DONE', simper_teory_test='DONE', simper_practice_test='DONE', simper_ojt='On Progress ', simper_status='On Progress On Progress ';
INSERT INTO employees SET id = 'C030231GEDE', full_name= 'GEDE WARDANA', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C030231', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-06-03', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='On Progress ', simper_status='On Progress On Progress ';
INSERT INTO employees SET id = 'C029786IMAM', full_name= 'IMAM FAUZAN', company_name='PT Pelangi Utama Jaya Mandiri', position='SPV Operation', employee_id='C029786', bpjs_tenaker_no='DONE (BPJS KES)', bpjs_kes_no='DONE (BPJS KES)', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-06-06', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030054IMZAL', full_name= 'IMZAL', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Bulldozer', employee_id='C030054', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-06-06', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030248MUNIF', full_name= 'MUNIF MAFANDA UNGGAHI', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C030248', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-06-06', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030080ANDIKA', full_name= 'ANDIKA NUARI PRASABDA', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Vibro', employee_id='C030080', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-06-06', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C028693NANDA', full_name= 'NANDA RIZKI DWI YULIYANTO', company_name='PT Pelangi Utama Jaya Mandiri', position='Mekanik', employee_id='C028693', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-05-31', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='Cuti', simper_status='On Progress On Progress ';
INSERT INTO employees SET id = 'C027691SUBUR', full_name= 'SUBUR WALUTYO', company_name='PT Pelangi Utama Jaya Mandiri', position='Mekanik', employee_id='C027691', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C028679ALFAN', full_name= 'ALFAN YUDHI ASMARA', company_name='PT Pelangi Utama Jaya Mandiri', position='Mekanik', employee_id='C028679', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-06-03', mine_permit_scm='DONE', simper_teory_test='N/A', simper_practice_test='N/A', simper_ojt='N/A', simper_status='N/AN/A';
INSERT INTO employees SET id = 'C027638Topan', full_name= 'Topan Sandi', company_name='PT Pelangi Utama Jaya Mandiri', position='PJO', employee_id='C027638', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-05-04', mine_permit_scm='DONE', simper_teory_test='N/A', simper_practice_test='N/A', simper_ojt='N/A', simper_status='N/AN/A';
INSERT INTO employees SET id = 'C027633Ikhlasul', full_name= 'Ikhlasul Zul Amal', company_name='PT Pelangi Utama Jaya Mandiri', position='Foreman Safety', employee_id='C027633', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-30', mine_permit_scm='DONE', simper_teory_test='N/A', simper_practice_test='N/A', simper_ojt='N/A', simper_status='N/AN/A';
INSERT INTO employees SET id = 'C027369Wardiansyah', full_name= 'Wardiansyah', company_name='PT Pelangi Utama Jaya Mandiri', position='Foreman Operation', employee_id='C027369', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-04', mine_permit_scm='DONE', simper_teory_test='N/A', simper_practice_test='N/A', simper_ojt='N/A', simper_status='N/AN/A';
INSERT INTO employees SET id = 'C027387Jade', full_name= 'Jade Tando', company_name='PT Pelangi Utama Jaya Mandiri', position='Engineer', employee_id='C027387', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='2026-04-04', mine_permit_scm='DONE', simper_teory_test='N/A', simper_practice_test='N/A', simper_ojt='N/A', simper_status='N/AN/A';
INSERT INTO employees SET id = 'C029782MULAHIZUN', full_name= 'MULAHIZUN AMIN', company_name='PT Pelangi Utama Jaya Mandiri', position='Foreman', employee_id='C029782', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029854SUKWAR', full_name= 'SUKWAR ASHARI', company_name='PT Pelangi Utama Jaya Mandiri', position='SPV Operation', employee_id='C029854', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030052PANGERAN', full_name= 'PANGERAN', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Bulldozer', employee_id='C030052', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030071HENDRIK', full_name= 'HENDRIK', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Vibro', employee_id='C030071', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030159MUHARAM', full_name= 'MUHARAM S', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C030159', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030191KASMAN', full_name= 'KASMAN', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C030191', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030235IDUL', full_name= 'IDUL ETENDING', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C030235', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030241HASRAN', full_name= 'HASRAN', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C030241', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='DONE', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030156MUH', full_name= 'MUH. SIDDIQ', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C030156', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030098M' ,full_name= 'M FATHIR ANDREAS', company_name='PT Pelangi Utama Jaya Mandiri', position='Fuelman', employee_id='C030098', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029715HERPITO', full_name= 'HERPITO', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C029715', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029726NOVARDIN', full_name= 'NOVARDIN', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C029726', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029733ADAM', full_name= 'ADAM SETIAWAN', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C029733', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030163HASNUR', full_name= 'HASNUR JAYA', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C030163', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030246MUH', full_name= 'MUH JALIL', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C030246', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029779WAYAN', full_name= 'WAYAN SUKRAYASA', company_name='PT Pelangi Utama Jaya Mandiri', position='Foreman', employee_id='C029779', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029784ARHAM', full_name= 'ARHAM', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver LV', employee_id='C029784', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030190ISAK', full_name= 'ISAK JURAHMAN', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C030190', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='DONE', mine_permit='DONE',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030197DEDI', full_name= 'DEDI SETYAWAN', company_name='PT Pelangi Utama Jaya Mandiri', position='Foreman', employee_id='C030197', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Revisi Medik', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029800ARJUN', full_name= 'ARJUN', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029800', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Revisi Medik', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029787KAMARUDDIN', full_name= 'KAMARUDDIN', company_name='PT Pelangi Utama Jaya Mandiri', position='PJO Hauling', employee_id='C029787', bpjs_tenaker_no='DONE ( FOTO)', bpjs_kes_no='DONE ( FOTO)', merdeka_sehat='Revisi Medik', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029721IWAN', full_name= 'IWAN', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C029721', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Revisi Medik', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029687MIRVAN', full_name= 'MIRVAN ABADI', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C029687', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Unfit', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029975HARDI', full_name= 'HARDI', company_name='PT Pelangi Utama Jaya Mandiri', position='OP  Grader', employee_id='C029975', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='Unfit', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029689RISAL', full_name= 'RISAL', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029689', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029665RAMLI', full_name= 'RAMLI', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029665', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029694USRAN', full_name= 'USRAN', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029694', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029804ARDAN', full_name= 'ARDAN', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029804', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029712ASRIANTO', full_name= 'ASRIANTO', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029712', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029811SYAHRUL', full_name= 'SYAHRUL RAMADHAN', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029811', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029812FERDY', full_name= 'FERDY DWI ARASDHAN', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029812', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029814JUSLAN', full_name= 'JUSLAN', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029814', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029720SENDI', full_name= 'SENDI ARDIYANSA', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029720', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029816FITRA', full_name= 'FITRA RAMADANA', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029816', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029724RESA', full_name= 'RESA', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029724', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029740MUH', full_name= 'MUH. RISAL', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029740', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029785M' ,full_name= 'M. DZIKRA BUMY', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C029785', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029730INDRA', full_name= 'INDRA ARDIANTO', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C029730', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029889AKBAR', full_name= 'AKBAR SK LAMANI', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C029889', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029952FERDI', full_name= 'FERDI', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C029952', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029908DIKI', full_name= 'DIKI ARIS WIRANDA', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C029908', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029739GUSTIAWAN', full_name= 'GUSTIAWAN', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029739', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029742LA', full_name= 'LA SURIADIN', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029742', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029898RIFAN', full_name= 'RIFAN PERMANA PUTRA', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029898', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029745NELSON', full_name= 'NELSON YOHANIS', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Bulldozer', employee_id='C029745', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029744ADHIM', full_name= 'ADHIM PUTRA', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver LV', employee_id='C029744', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029853FAHRUL', full_name= 'FAHRUL ROZI', company_name='PT Pelangi Utama Jaya Mandiri', position='SPV. Logistick & Fuel', employee_id='C029853', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030214MIFTAH', full_name= 'MIFTAH HUJANNAH', company_name='PT Pelangi Utama Jaya Mandiri', position='Data Mine Engineer', employee_id='C030214', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029756LARISMAN', full_name= 'LARISMAN', company_name='PT Pelangi Utama Jaya Mandiri', position='Foreman', employee_id='C029756', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029761SUL', full_name= 'SUL FIKAR', company_name='PT Pelangi Utama Jaya Mandiri', position='Foreman Operation', employee_id='C029761', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029749ISDAR', full_name= 'ISDAR HARUN', company_name='PT Pelangi Utama Jaya Mandiri', position='Jr Mekanik', employee_id='C029749', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029743MUHAMMAD', full_name= 'MUHAMMAD AGUNG BAHARI', company_name='PT Pelangi Utama Jaya Mandiri', position='Tyreman', employee_id='C029743', bpjs_tenaker_no='Progress Econ', bpjs_kes_no='Progress Econ', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029845FATUR', full_name= 'FATUR RAHMAN', company_name='PT Pelangi Utama Jaya Mandiri', position='Fuelman', employee_id='C029845', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029847AMARULLAH', full_name= 'AMARULLAH', company_name='PT Pelangi Utama Jaya Mandiri', position='Fuelman', employee_id='C029847', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030091SARMAN', full_name= 'SARMAN', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver Fuelman', employee_id='C030091', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029851ANSAR', full_name= 'ANSAR', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver Fuelman', employee_id='C029851', bpjs_tenaker_no='DONE ( FOTO)', bpjs_kes_no='DONE ( FOTO)', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029757MUH', full_name= 'MUH. FAJAR SUSANTO', company_name='PT Pelangi Utama Jaya Mandiri', position='Foreman', employee_id='C029757', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029943MUH', full_name= 'MUH. IRFAN', company_name='PT Pelangi Utama Jaya Mandiri', position='Foreman', employee_id='C029943', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029883AGUS', full_name= 'AGUS SALIM', company_name='PT Pelangi Utama Jaya Mandiri', position='OP  Grader', employee_id='C029883', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029885MUHAMAD', full_name= 'MUHAMAD GUNTUR MANSUR', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029885', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029894IKHWAN', full_name= 'IKHWAN', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029894', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029900IRMANTO', full_name= 'IRMANTO', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C029900', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029953AHMAD', full_name= 'AHMAD', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver LV', employee_id='C029953', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C029979EMAN', full_name= 'EMAN SULFAJAR', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver LV', employee_id='C029979', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030088MUH', full_name= 'MUH ARIL SAPUTRA', company_name='PT Pelangi Utama Jaya Mandiri', position='Fuelman', employee_id='C030088', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030093ZAINAL', full_name= 'ZAINAL YUSRIN', company_name='PT Pelangi Utama Jaya Mandiri', position='Fuelman', employee_id='C030093', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030143LA', full_name= 'LA ODE NAZARUDDIN', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C030143', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030144RELI', full_name= 'RELI', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C030144', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030145ADHY', full_name= 'ADHY WIJAYA', company_name='PT Pelangi Utama Jaya Mandiri', position='OP Exca', employee_id='C030145', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030146KENDAR', full_name= 'KENDAR', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C030146', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030192LA', full_name= 'LA ODE SAMSUL DIMANTARA', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C030192', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030210WA', full_name= 'WA ODE MIFTAHUL HAYAT', company_name='PT Pelangi Utama Jaya Mandiri', position='Jr. Data ME', employee_id='C030210', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030218ANANDA', full_name= 'ANANDA LIFARI', company_name='PT Pelangi Utama Jaya Mandiri', position='Admin HR', employee_id='C030218', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030203RUHUL', full_name= 'RUHUL SUNAN JAZIRAH', company_name='PT Pelangi Utama Jaya Mandiri', position='Foreman Hauling', employee_id='C030203', bpjs_tenaker_no='DONE(BPJS KES)', bpjs_kes_no='DONE(BPJS KES)', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';
INSERT INTO employees SET id = 'C030244M', full_name= 'M ADI HANDRIYADIN', company_name='PT Pelangi Utama Jaya Mandiri', position='Driver DT', employee_id='C030244', bpjs_tenaker_no='DONE', bpjs_kes_no='DONE', merdeka_sehat='Progress Merdeka Sehat', mine_permit='On Progress ',induction_schedule='0000-00-00', mine_permit_scm='On Progress ', simper_teory_test='', simper_practice_test='', simper_ojt='', simper_status='';'