ALTER TABLE employee_timesheets 
ADD COLUMN keterangan TEXT DEFAULT NULL,
ADD COLUMN overtime_type ENUM('NONE', 'BIASA', 'LIBUR') DEFAULT 'NONE',
ADD COLUMN overtime_start TIME NULL,
ADD COLUMN overtime_end TIME NULL,
ADD COLUMN hm_awal_lembur DECIMAL(10,2) NULL,
ADD COLUMN hm_akhir_lembur DECIMAL(10,2) NULL,
ADD COLUMN overtime_amount DECIMAL(15,2) DEFAULT 0;

INSERT INTO settings (id, setting_key, setting_value, setting_desc, created_at) 
VALUES (UUID(), 'tarif_lembur', '19505', 'Tarif dasar lembur per jam', NOW());

ALTER TABLE `employees` ADD `join_date` DATE NULL DEFAULT NULL AFTER `position`;

INSERT INTO employees (id, full_name, position, join_date) VALUES ('08TOPAN', 'TOPAN SANDI', 'PJO', '2026-04-08');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12KAMARUDDIN', 'KAMARUDDIN', 'PJO HAULING', '2026-02-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('15FERDY', 'FERDY ANDRYAN', 'HRD', '2023-12-15');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('25IRWAN', 'IRWAN', 'SPV OPERATION', '2026-03-25');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('08BAGUS', 'BAGUS HANDHOKO', 'SPV OPERATION', '2026-04-08');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('18MUH', 'MUH. DZUL IQRAM KAR. MS', 'SPV. HSE', '2026-04-18');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('31FAHRUL', 'FAHRUL ROZI', 'SPV. LOGISTIK & FUEL', '');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('17SULTAN', 'SULTAN THAHA ARAFAT FATAHILLAH', 'MAINPLAN', '2026-01-17');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('17MIFTAH', 'MIFTAH HUJANNAH', 'DATA MINE ENGINEER', '2026-02-17');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01JADE', 'JADE TANDO', 'Jr. MINE PLAN', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('08LARISMAN', 'LARISMAN', 'FOREMAN', '2026-01-08');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29WARDIANSYAH', 'WARDIANSYAH', 'FOREMAN', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29MUHAMMAD', 'MUHAMMAD FAJAR SUSANTO', 'FOREMAN', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('04MUH', 'MUH. IRFAN', 'FOREMAN', '2026-02-04');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01SUL', 'SUL FIKAR', 'FOREMAN OPERATION', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01SUBNEDI', 'SUBNEDI. HT', 'FOREMAN', '2026-03-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('31HENDRI', 'HENDRI', 'FOREMAN', '');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('16WAYAN', 'WAYAN SUKRAYASA', 'FOREMAN', '2026-04-16');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('16MULAHIZUN', 'MULAHIZUN AMIN', 'FOREMAN', '2026-04-16');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('11IKHLAS', 'IKHLAS ZUL AMAL', 'SAFETY', '2026-04-11');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('27ARHAM', 'ARHAM', 'SAFETY', '2026-04-27');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('08RAHMAD', 'RAHMAD', 'HRD STAFF', '2026-01-08');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('16AGNES', 'AGNES LINDA PASAMMAN', 'ADMIN FINANCE', '2026-02-16');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('31ANANDA', 'ANANDA LIFARI', 'ADMIN HR', '2026-01-31');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('02RINI', 'RINI TRIANI SAFITRI', 'ADMIN LOGISTIK', '2026-02-02');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('19SUBUR', 'SUBUR WALUYO', 'MEKANIK', '2026-01-19');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01NANDA', 'NANDA RIZKI DWI YULIYANTO', 'MEKANIK', '2026-03-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01ALFAN', 'ALFAN YUDHI ASMARA', 'MEKANIK', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('10ISDAR', 'ISDAR HARUN', 'Jr MEKANIK', '2026-03-10');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12SUGIATNO', 'SUGIATNO', 'WELDER', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12LEO', 'LEO EDY SUSANTO', 'WELDER', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12ANDY', 'ANDY KRISDIANTO', 'WELDER', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12SARBIN', 'SARBIN', 'WELDER', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12AHMAD', 'AHMAD SOLEH', 'WELDER', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12MUNALIM', 'MUNALIM', 'WELDER', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01MUHAMMAD', 'MUHAMMAD AGUNG BAHARI', 'TYREMAN', '2026-01-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('28FATUR', 'FATUR RAHMAN', 'FUELMAN', '2026-01-28');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('14MUH', 'MUH. ARIL SAPUTRA', 'FUELMAN', '2026-03-14');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01AMARULLAH', 'AMARULLAH', 'FUELMAN', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('14ZAINAL', 'ZAINAL YUSRIN', 'FUELMAN', '2026-04-14');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('28M', 'M FATHIR ANDREAS', 'FUELMAN', '2026-04-28');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('09YUSDIN', 'YUSDIN', 'OPERATOR EXCA', '2026-01-09');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('09ARJUN', 'ARJUN', 'OPERATOR EXCA', '2026-01-09');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('14YUSRIN', 'YUSRIN', 'OPERATOR EXCA', '2026-01-14');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('14RISAL', 'RISAL', 'OPERATOR EXCA', '2026-01-14');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('16ISRAN', 'ISRAN', 'OPERATOR EXCA', '2026-01-16');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29RAMLI', 'RAMLI', 'OPERATOR EXCA', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29A', 'A. ALI IMRAN JABAR', 'OPERATOR EXCA', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29USRAN', 'USRAN', 'OPERATOR EXCA', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29JASRIN', 'JASRIN', 'OPERATOR EXCA', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29LA', 'LA SURIADIN', 'OPERATOR EXCA', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29ARDAN', 'ARDAN', 'OPERATOR EXCA', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29ABD', 'ABD. HAMID', 'OPERATOR EXCA', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29ASRIANTO', 'ASRIANTO', 'OPERATOR EXCA', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29SYAHRUL', 'SYAHRUL RAMADHAN', 'OPERATOR EXCA', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('04GAUSU', 'GAUSU A', 'OPERATOR EXCA', '2026-02-04');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('04FERDY', 'FERDY DWI ARASDHAN', 'OPERATOR EXCA', '2026-02-04');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('04JUSLAN', 'JUSLAN', 'OPERATOR EXCA', '2026-02-04');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('04AFRUL', 'AFRUL', 'OPERATOR EXCA', '2026-02-04');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('04SENDI', 'SENDI ARDIYANSA', 'OPERATOR EXCA', '2026-02-04');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('04FITRA', 'FITRA RAMADANA', 'OPERATOR EXCA', '2026-02-04');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('04RESA', 'RESA', 'OPERATOR EXCA', '2026-02-04');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('04ASRIADI', 'ASRIADI', 'OPERATOR EXCA', '2026-02-04');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('04ETTUIN', 'ETTUIN', 'OPERATOR EXCA', '2026-02-04');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('08MUH', 'MUH. RISAL', 'OPERATOR EXCA', '2026-02-04');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('10LA', 'LA ODE NAZARUDIN', 'OPERATOR EXCA', '2026-03-10');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01SARMAN', 'SARMAN', 'OPERATOR EXCA', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('03RELI', 'RELI', 'OPERATOR EXCA', '2026-04-03');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('03ADHY', 'ADHY WIJAYA', 'OPERATOR EXCA', '2026-04-03');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('03GUSTIAWAN', 'GUSTIAWAN', 'OPERATOR EXCA', '2026-04-03');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('03MARIUDIN', 'MARIUDIN', 'OPERATOR EXCA', '2026-04-03');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('03RIFAN', 'RIFAN PERMANA PUTRA', 'OPERATOR EXCA', '2026-04-03');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('14IKHWAN', 'IKHWAN', 'OPERATOR EXCA', '2026-04-14');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('14IRMANTO', 'IRMANTO', 'OPERATOR EXCA', '2026-04-14');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('14DAPIT', 'DAPIT', 'OPERATOR EXCA', '2026-04-14');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('15SAKIR', 'SAKIR', 'OPERATOR EXCA', '2026-04-15');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('15RUSDIN', 'RUSDIN', 'OPERATOR EXCA', '2026-04-15');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('16RAHMAT', 'RAHMAT HIDAYAT ANWAR', 'OPERATOR EXCA', '2026-04-16');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('16MUH', 'MUH. SIDDIQ', 'OPERATOR EXCA', '2026-04-16');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('17ZIDAN', 'ZIDAN FIRNIAWAN', 'OPERATOR EXCA', '2026-04-17');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('17KHAIRUL', 'KHAIRUL FAJAR', 'OPERATOR EXCA', '2026-04-17');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('17ALIMIN', 'ALIMIN', 'OPERATOR EXCA', '2026-04-17');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('17YUSMIN', 'YUSMIN', 'OPERATOR EXCA', '2026-04-17');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('17LINTO', 'LINTO', 'OPERATOR EXCA', '2026-04-17');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('19FIRMANSYAH', 'FIRMANSYAH', 'OPERATOR EXCA', '2026-04-19');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('19ERWIN', 'ERWIN', 'OPERATOR EXCA', '2026-04-19');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('19SAMSON', 'SAMSON', 'OPERATOR EXCA', '2026-04-19');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22MUHAMMAD', 'MUHAMMAD JUMADDIN K', 'OPERATOR EXCA', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22PATLI', 'PATLI PASAURAN', 'OPERATOR EXCA', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22ILHAM', 'ILHAM ARDIYANSYAH', 'OPERATOR EXCA', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22MUCHAMMAD', 'MUCHAMMAD DHIKY JULIANSYAH', 'OPERATOR EXCA', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22REVANGGA', 'REVANGGA ANGGUN NUGROHO', 'OPERATOR EXCA', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22SUTRISNO', 'SUTRISNO', 'OPERATOR EXCA', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22GUNTUR', 'GUNTUR TEGAR NUR SAPUTRA', 'OPERATOR EXCA', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22ALFIANT', 'ALFIANT OCTA ANGGARAPUTRE', 'OPERATOR EXCA', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22REZA', 'REZA APRIANSYAH', 'OPERATOR EXCA', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22RIZWAN', 'RIZWAN ISKANDAR', 'OPERATOR EXCA', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29IKSAN', 'IKSAN', 'OPERATOR BREAKER', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('15MARIADI', 'MARIADI', 'OPERATOR BREAKER', '2026-04-15');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('16EDWARD', 'EDWARD', 'OPERATOR BREAKER', '2026-04-16');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22JUNERDI', 'JUNERDI', 'OPERATOR BREAKER', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('16DEDI', 'DEDI SURYADI', 'OPERATOR DOZER', '2026-01-16');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('04NELSON', 'NELSON YOHANIS', 'OPERATOR DOZER', '2026-02-04');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01M', 'M.SYUKUR', 'OPERATOR DOZER', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01ASRAN', 'ASRAN LAMIO', 'OPERATOR DOZER', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('15MUH', 'MUH. ALFIAN', 'OPERATOR DOZER', '2026-04-15');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('15JUSRIN', 'JUSRIN', 'OPERATOR DOZER', '2026-04-15');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22IMZAL', 'IMZAL', 'OPERATOR DOZER', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22SUPRIADI', 'SUPRIADI', 'OPERATOR DOZER', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22PANGERAN', 'PANGERAN', 'OPERATOR DOZER', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22JUMARDIN', 'JUMARDIN MOITA', 'OPERATOR DOZER', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22DIMAN', 'DIMAN SETIAWAN', 'OPERATOR DOZER', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('03YUSRAN', 'YUSRAN', 'OPERATOR VIBRO', '2026-04-03');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('16ANDIKA', 'ANDIKA NUARI PRASABDA', 'OPERATOR VIBRO', '2026-04-16');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('16ANDRIANSYAH', 'ANDRIANSYAH', 'DRIVER WT', '2026-04-16');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('19HENDRIK', 'HENDRIK', 'OPERATOR VIBRO', '2026-04-19');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22ULIL', 'ULIL ALBAB', 'OPERATOR VIBRO', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('29ADIT', 'ADIT', 'OPERATOR GREADER', '2026-01-29');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('22HARDI', 'HARDI', 'OPERATOR GREADER', '2026-04-22');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01ANDRI', 'ANDRI AFIYANTO', 'DRIVER DT', '2025-12-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01JONI', 'JONI HARIYANTO', 'DRIVER DT', '2025-12-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01SAMSUL', 'SAMSUL ANWAR', 'DRIVER DT', '2025-12-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('10MUHAMMAD', 'MUHAMMAD JALIL', 'DRIVER DT', '2026-03-10');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('03M', 'M. DZIKRA BUMY', 'DRIVER DT', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01RINO', 'RINO', 'DRIVER DT', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01HERDIN', 'HERDIN', 'DRIVER DT', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01ABRAHAM', 'ABRAHAM TRIYADI', 'DRIVER DT', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01ADAM', 'ADAM YORDAN', 'DRIVER DT', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01SYAFARUDDIN', 'SYAFARUDDIN YUNUS', 'DRIVER DT', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01INDRA', 'INDRA ARDIANTO', 'DRIVER DT', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12HERPITO', 'HERPITO', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12MIRVAN', 'MIRVAN ABADI', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12IWAN', 'IWAN', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12AKBAR', 'AKBAR SK LAMANI', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12NOVARDIN', 'NOVARDIN', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12RAHMAN', 'RAHMAN', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12ISRA', 'ISRA JAYA', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12ADAM', 'ADAM SETIAWAN', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12GEDE', 'GEDE WARDANA', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12FERDI', 'FERDI', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12DIKI', 'DIKI ARIS WIRANDA', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12KENDAR', 'KENDAR', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('12MUHARAM', 'MUHARAM. S', 'DRIVER DT', '2026-04-12');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('13HASRAN', 'HASRAN', 'DRIVER DT', '2026-04-13');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('13IDUL', 'IDUL ENTENDING', 'DRIVER DT', '2026-04-13');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('13ISAK', 'ISAK JURAHMAN', 'DRIVER DT', '2026-04-13');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('13HASNUR', 'HASNUR JAYA', 'DRIVER DT', '2026-04-13');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('13M', 'M. ADI HANDRIYADIN', 'DRIVER DT', '2026-04-13');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('15KASMAN', 'KASMAN', 'DRIVER DT', '2026-04-15');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('15LA', 'LA ODE SAMSUL DIMANTARA', 'DRIVER DT', '2026-04-15');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('16AHMAD', 'AHMAD', 'DRIVER LV', '2023-12-16');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('14EMAN', 'EMAN SUFAJAR', 'DRIVER LV', '2026-04-14');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01SYAMSUL', 'SYAMSUL BAHRI', 'DRIVER LV', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01IMANUEL', 'IMANUEL GUSTIAWAN LAPIK', 'DRIVER LV', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01ADHIM', 'ADHIM PUTRA', 'DRIVER LV', '2026-04-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('14SARMAN', 'SARMAN', 'DRIVER FUEL', '2026-04-14');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('09ANSAR', 'ANSAR', 'DRIVER FUEL', '2026-04-09');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('28JUMADIL', 'JUMADIL', 'WAKAR', '2025-12-28');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('08NURLIN', 'NURLIN', 'WAKAR', '2026-02-08');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('16ARIF', 'ARIF', 'WAKAR', '2026-03-16');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('09RESA', 'RESA ASRIANI', 'ART', '2026-04-09');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('28MUHAMMAD', 'MUHAMMAD FADLI ATTHAAILLAH', 'SAFETYMAN', '2026-04-28');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01MUNIF', 'MUNIF MAFANDA UNGGAR', 'DRIVER DT', '2026-05-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26RUHUL', 'RUHUL SUNAN JAZIROH R.A', 'FOREMAN HAULING', '3-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26ANDRI', 'ANDRI', 'CHECKER', '5-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26PRAYOGA', 'PRAYOGA', 'CHECKER', '5-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26M', 'M ASBAR', 'DRIVER LV', '5-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26YUDA', 'YUDA TRI LESTYANTO', 'Jr. MEKANIK', '5-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26IKSAN', 'IKSAN', 'OPERATOR EXCA', '5-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26SALDA', 'SALDA TODING', 'OPERATOR DOZER', '5-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26AGUS', 'AGUS SALIM', 'OPERATOR GREADER', '5-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26SYUKRI', 'SYUKRI GAIS', 'SPV TRAINER', '5-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26SELFIANA', 'SELFIANA', 'ADMIN GA', '5-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26EKA', 'EKA PRADANA PUTRA', 'OPERATOR EXCA', '7-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26MUHAMAD', 'MUHAMAD GUNTUR MANSUR', 'OPERATOR EXCA', '7-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26MUH', 'MUH. RUSLI M', 'TYREMAN', '7-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26SUKWAR', 'SUKWAR ASHARI', 'SPV OPERATION', '8-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26IMAM', 'IMAM FAUZAN', 'SPV OPERATION', '12-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26ARJUNA', 'ARJUNA RANNI KAYANG', 'OPERATOR EXCA', '12-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26ALDI', 'ALDI MUIN', 'OPERATOR EXCA', '12-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26WA', 'WA ODE MIFTAHUL HAYAT', 'JR DATA MINE E.', '17-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26RIDHO', 'RIDHO WIJAYA SAPUTRA', 'Jr. MEKANIK', '17-May-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('20NASRUN', 'NASRUN A. LATIF', 'DRIVER LV', '2026-05-20');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('26RIJAL', 'RIJAL', 'SAFETYMAN', '2026-05-26');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('30ERIK', 'ERIK FADLI', 'DRIVER MANHAUL', '2026-05-30');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('30DEDI', 'DEDI SETYAWAN', 'FOREMAN', '2026-05-30');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('01A', 'A. RADENG', 'CREW HOUSEKEEPING', '2026-06-01');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('03NABILA', 'NABILA KEISHA RAMADNIYA', 'ADMIN HAULING', '2026-06-03');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('03INDRA', 'INDRA', 'GA STAFF', '2026-06-03');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('07ABDI', 'ABDI BALA', 'FOREMAN HRD', '2026-06-07');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('08FERDIANSYAH', 'FERDIANSYAH', 'DRIVER LV FUEL', '2026-06-08');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('11HUDA', 'HUDA', 'STAFF LOGISTIK', '2026-06-11');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('11GITA', 'GITA ANGGI SETIAWAN', 'Jr. MEKANIK', '2026-06-11');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('11LUTFI', 'LUTFI DWI YUDHA SAPUTRA', 'Jr. MEKANIK', '2026-06-11');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('11GALANG', 'GALANG', 'GRASEMAN', '2026-06-11');
INSERT INTO employees (id, full_name, position, join_date) VALUES ('11SUPRIADI', 'SUPRIADI', 'MEKANIK ELECTRICAL', '2026-06-11');