name: Deploy to VPS

on:
  push:
    branches:
      - main  # Setiap kamu push ke branch main, dia jalan otomatis

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 195.88.211.139
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /www/wwwroot/mtc.armadamix.id
            # Bersihkan lock atau stale ref jika terjadi desync
            rm -f .git/refs/remotes/origin/main
            rm -f .git/refs/remotes/origin/main.lock
            git fetch --prune origin
            git reset --hard origin/main
